version: "3.9"
services:
  my-express:
    image: my-express-container
    container_name: my-express-api
    build:
      context: .
    ports:
      - "8001:8000"

  my_mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_mysql_db
    ports:
      - "3300:3300"
    volumes:
      - my_volume:/var/lib/mysql

volumes:
  my_volume:
